// Generated by CoffeeScript 1.11.1
(function() {
  var should, user;

  should = require('should');

  user = require('../lib/user');

  describe('User', function() {
    describe('#get()', function() {
      it('should execute the callback', function() {
        var tmp;
        tmp = user.get("jack", function(user) {
          return user;
        });
        should.equal("jack", tmp);
      });
    });
    describe('#save()', function() {
      it('should execute the callback', function() {
        var tmp;
        tmp = user.save("jack", function(user) {
          return user;
        });
        should.equal("jack", tmp);
      });
    });
  });

}).call(this);
