// Generated by CoffeeScript 1.11.1
(function() {
  var should, user;

  should = require('should');

  user = require('../lib/user');

  describe('User', function() {
    describe('#get()', function() {
      return it('should execute the callback', function() {
        return user.get("lgrondin", function(err, value) {
          console.log(value);
          console.log(err);
          return should.equal(lgrondin, value.username);
        });
      });
    });
    describe('#save()', function() {
      it('should execute the callback', function() {
        var tmp;
        tmp = user.save("jack", function(user) {
          return user;
        });
        should.equal("jack", tmp);
      });
    });
  });

}).call(this);
