// Generated by CoffeeScript 1.11.1
(function() {
  var app, authCheck, bodyparser, express, levelStore, metrics, morgan, nib, session, stylus, user;

  express = require('express');

  session = require('express-session');

  levelStore = require('level-session-store')(session);

  metrics = require('./metrics');

  user = require('./user');

  morgan = require('morgan');

  bodyparser = require('body-parser');

  stylus = require('stylus');

  nib = require('nib');

  app = express();

  app.use(morgan('dev'));

  app.use(stylus.middleware({
    src: __dirname + '/../stylesheets',
    dest: __dirname + '/../public/css',
    compile: function(str, path) {
      return stylus(str).set('filename', path).set('compress', true).use(nib())["import"]('nib');
    }
  }));

  app.use(bodyparser.json());

  app.use(bodyparser.urlencoded({
    extended: true
  }));

  app.set('port', 1337);

  app.use(session({
    secret: 'metricsApp',
    store: new levelStore('./db/session'),
    resave: true,
    saveUninitialized: true,
    cookie: {
      secure: true
    }
  }));

  authCheck = function(req, res, next) {
    if (req.session.loggedIn === true) {
      return next();
    } else {
      return res.redirect('/signin');
    }
  };

  app.set('view engine', 'pug');

  app.set('views', __dirname + "/../views");

  app.use('/', express["static"](__dirname + "/../public"));

  app.get('/', function(req, res) {
    return res.redirect('/login');
  });

  app.get('/login', function(req, res) {
    var base;
    console.log("Login Error : " + req.query.error);
    return res.render('login', {
      error: (base = req.query).error != null ? base.error : base.error = ''
    });
  });

  app.post('/login', function(req, res) {
    return user.get(req.body.username, req.body.password, function(err, value) {
      if (err) {
        console.log(err);
        req.params.error = err;
        return res.redirect('/login' + '/?error=' + err);
      } else {
        return res.render('user-layout', {
          user: value
        });
      }
    });
  });

  app.get('/app', function(req, res) {
    return res.end('Salut tout le monde !');
  });

  app.get('/metrics.json', function(req, res) {
    return metrics.get(function(err, data) {
      if (err) {
        throw next(err);
      }
      return res.status(200).json(data);
    });
  });

  app.get('/metrics', function(req, res) {
    return res.render('metrics-layout');
  });

  app.put('/signup', function(req, res) {
    return user.save(req.body.username, req.body.name, req.body.password, req.body.email, function(err) {
      if (err) {
        throw err;
      }
      return res.status(200).send();
    });
  });

  app.get('/users', function(req, res) {
    return user.get(function(err, data) {
      if (err) {
        throw err;
      }
      return res.render('user-layout');
    });
  });

  app.get('/user/:username', function(req, res) {
    return user.get(req.params.username, function(err, value) {
      if (err) {
        return res.render('error', {
          error: err
        });
      } else {
        return res.render('user-layout', {
          user: value
        });
      }
    });
  });

  app.listen(app.get('port'), function() {
    return console.log("listen on port " + (app.get('port')));
  });

}).call(this);
