// Generated by CoffeeScript 1.11.1
(function() {
  var app, bodyparser, express, metrics, morgan, user;

  express = require('express');

  metrics = require('./metrics');

  user = require('./user');

  morgan = require('morgan');

  bodyparser = require('body-parser');

  app = express();

  app.use(morgan('dev'));

  app.use(bodyparser.json());

  app.set('port', 1337);

  app.set('view engine', 'pug');

  app.set('views', __dirname + "/../views");

  app.use('/', express["static"](__dirname + "/../public"));

  app.get('/', function(req, res) {
    return res.send("hello world !");
  });

  app.get('/hello/:name', function(req, res) {
    return res.render('layout', {
      name: req.params.name
    });
  });

  app.get('/metrics.json', function(req, res) {
    return metrics.get(function(err, data) {
      if (err) {
        throw next(err);
      }
      return res.status(200).json(data);
    });
  });

  app.get('/metrics', function(req, res) {
    return res.render('metrics-layout');
  });

  app.put('/signup', function(req, res) {
    return user.save(req.body.username, req.body.name, req.body.password, req.body.email, function(err) {
      if (err) {
        throw err;
      }
      return res.status(200).send();
    });
  });

  app.get('/users', function(req, res) {
    return user.get(function(err, data) {
      if (err) {
        throw err;
      }
      return res.render('user-layout');
    });
  });

  app.get('/user/:username', function(req, res) {
    return user.get(req.params.username, function(err, value) {
      if (err) {
        res.render('error', {
          error: err
        });
        return res.status(err).send();
      } else {
        res.render('user-layout', {
          username: req.params.username,
          user: value
        });
        return res.status(200).send();
      }
    });
  });

  app.listen(app.get('port'), function() {
    return console.log("listen on port " + (app.get('port')));
  });

}).call(this);
