// Generated by CoffeeScript 1.11.1
(function() {
  var db, shortid;

  db = require('./db')("metrics");

  shortid = require('shortid');

  module.exports = {
    get: function(username, callback) {
      console.log([
        {
          timestamp: (new Date('2013-11-04 14:00 UTC')).getTime(),
          value: 1
        }
      ]);
      return callback(null, [
        {
          timestamp: (new Date('2013-11-04 14:00 UTC')).getTime(),
          value: 1
        }, {
          timestamp: (new Date('2013-11-04 14:30 UTC')).getTime(),
          value: 2
        }
      ]);
    },
    save: function(username, metric, callback) {
      if (username && metric.timestamp && metric.value) {
        return db.put((shortid.generate()) + ":" + username, metric.timestamp + ":" + metric.value, function(err) {
          if (err) {
            return callback(err);
          } else {
            console.log("timestamp :  " + metric.timestamp + ", value: " + metric.value + " add for " + username);
            return callback();
          }
        });
      } else {
        return callback("metric is empty");
      }
    }
  };

}).call(this);
