// Generated by CoffeeScript 1.11.1
(function() {
  var db, shortid;

  db = require('./db')("metrics");

  shortid = require('shortid');

  module.exports = {
    get: function(username, callback) {
      return callback(null);
    },
    get: function(username, groupe, callback) {
      return callback(null);
    },
    save: function(username, metrics, callback) {
      var i, len, metric, ws;
      console.log("Save some metrics");
      ws = db.createWriteStream();
      ws.on('error', callback);
      ws.on('close', callback);
      for (i = 0, len = metrics.length; i < len; i++) {
        metric = metrics[i];
        if (username && metric.groupe && metric.timestamp && metric.value) {
          metric.timestamp = new Date(metric.timestamp).getTime();
          if (metric.id) {
            ws.write({
              key: username + ":" + metric.groupe + ":" + metric.id,
              value: metric.timestamp + ":" + metric.value
            });
            console.log("Metric modified");
          } else {
            ws.write({
              key: username + ":" + metric.groupe + ":" + (shortid.generate()),
              value: metric.timestamp + ":" + metric.value
            });
            console.log("Metric created");
          }
        } else {
          callback("Missing some information in metric");
        }
      }
      return ws.end();
    }
  };

}).call(this);
