// Generated by CoffeeScript 1.11.1
(function() {
  module.exports = {
    get: function(user, callback) {
      return callback(user);
    },
    save: function(id, callback) {
      return callback(id);
    }
  };

}).call(this);
