// Generated by CoffeeScript 1.11.1
(function() {
  var db;

  db = require('./db')("user");

  module.exports = {
    get: function(username, password, callback) {
      return db.get(username, function(err, value) {
        var _email, _name, _password, ref;
        if (err) {
          return callback(err);
        } else {
          ref = value.split(':'), _password = ref[0], _name = ref[1], _email = ref[2];
          if (password !== _password) {
            console.log("Password not correct");
            return callback("Password not correct");
          }
          return callback(null, {
            name: _name,
            email: _email,
            username: username
          });
        }
      });
    },
    save: function(username, password, name, email, callback) {
      return db.put("" + username, password + ":" + name + ":" + email, function(err) {
        if (err) {
          return callback(err);
        } else {
          console.log('user ' + username + ' add');
          return callback();
        }
      });
    },
    remove: function(username, callback) {
      return callback(username);
    }
  };

}).call(this);
