// Generated by CoffeeScript 1.11.1
(function() {
  var db;

  db = require('./db')("user");

  module.exports = {
    get: function(callback) {
      return callback(null, db.createReadStream().on('data', function(data) {
        return console.log(data.key, '=', data.value);
      }).on('error', function(err) {
        return console.log('Oh my!', err);
      }).on('close', function() {
        return console.log('Stream closed');
      }).on('end', function() {
        return console.log('Stream ended');
      }));
    },
    post: function(user, callback) {
      var metrics, rs;
      metrics = [];
      consol.log(id);
      rs = db.createdReadStream()({
        start: "user:" + username,
        stop: "user:" + id
      }).on('data', function(data) {
        var _, _username, ref;
        ref = data.key.split(':'), _ = ref[0], _username = ref[1];
        return [];
      });
      rs.on('error', callback);
      return rs.on('close', function() {
        return callback(null, user);
      });
    },
    save: function(username, password, name, email, callback) {
      return db.put("" + username, name + ":" + password + ":" + email, function(err) {
        if (err) {
          return callback(err);
        } else {
          console.log('user ' + username + ' add');
          return callback();
        }
      });
    },
    remove: function(username, callback) {
      return callback(username);
    }
  };

}).call(this);
